### ISSUE TITLE
any updates regarding new stock? 

### ISSUE THREAD

**Issue by slastrina** [radensb/eZ_Navi-Delete#8]
Hi, just checking in if stock issues are resolved at all? Don't mind paying more if price point has increased.

Are the latest board files available otherwise? I might try assemble one locally as another option.

Keen to wrap up my dash with your board

**Comment by radensb** [comment]
I just created a discussions page that talks about this. Please feel free to review and comment there. Thanks!
https://github.com/radensb/eZ_Navi-Delete/discussions/9

**Comment by slastrina** [comment]
Cheers Mate
